AppAccount/urls.py
from django.urls import path
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)                            
from .import views
from .import forms



urlpatterns=[
    path('', views.loginUser, name="index"),
    path('account/logout', views.logoutUser,name='logoutUser'),
    path('account/change-password', views.changePassword, name="changePassword"),
    path('appropos-de-congeline', views.appropos, name="appropos"),
    path('contact', views.contact, name="contact"),
    path('account/profil-user', views.ProfilUser, name="ProfilUser"),
    path('account/change-profil=<str:id>', views.ChangeProfil, name='ChangeProfil'),
    path('guide-user', views.guideUser, name="guideUser"),

    #reinitialisation du mot de password utilisateur
    path('account/password_reset/', PasswordResetView.as_view(template_name='reset_password/password_reset.html', form_class=forms.Formpassword_reset),name='password_reset'),
    path('account/password_reset/done/',PasswordResetDoneView.as_view(template_name='reset_password/password_send_email.html'), name='password_reset_done'),
    path('account/reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name='reset_password/password_set_confirm.html', form_class=forms.FormSetPassword),name='password_reset_confirm'),
    path('account/reset/done/',PasswordResetCompleteView.as_view(template_name='reset_password/password_reset_complete.html'),name='password_reset_complete'),
    
]

AppConge/urls.py
from django.urls import path
from .import views


urlpatterns=[
    path('conge-user', views.CongeUser, name="CongeUser"),
    path('ajout-conge', views.ajoutConge, name="ajoutConge"),
    path('detailConge=<str:id>', views.detailConge,name="detailConge"),
    path('modifConge=<str:id>', views.modifConge, name="modifConge"),
    path('suppConge=<int:id>', views.suppConge, name='suppConge'),
    path('conge-attente', views.congeAttente, name='congeAttente'),
    path('approuve-rejet-conge', views.approuveRejetConge, name="approuveRejetConge"),
    path('conge-approuve', views.congeApprouve, name="congeApprouve"),
    path('conge-rejet', views.congeRejet, name="congeRejet"),
    path('conge-encours', views.congeEncours, name='congeEncours'),
    path('conge-attente-user', views.congeAttenteUser, name="congeAttenteUser"),
    path('liste-approbation-rejet', views.listeApprobationRejet, name="listeApprobationRejet"),
    path('modifApprobationRejet=<str:id>', views.modifApprobationRejet, name='modifApprobationRejet'),
    path('suppDemande=<str:id>', views.suppDemande, name="suppDemande"),
    path('detailDemande=<str:id>', views.detailDemande, name="detailDemande"),
    path('consulter-conge-encours', views.consulterCongeEncours, name="consulterCongeEncours"),
    path('detailCongeApprobateur=<str:id>', views.detailCongeApprobateur, name="detailCongeApprobateur"),
    path('stat-conge-annee', views.stat_conge_annee, name="stat_conge_annee"),
    path('export-csv-stat-conge_annee=<str:annee>', views.export_csv_stat_conge_annee, name="export_csv_stat_conge_annee"),
    path('detail-stat-conge-annee=<str:annee>', views.detail_stat_conge_annee, name = "detail_stat_conge_annee"),
    path('stat-classement-service-par-annee', views.stat_classement_service_par_annee, name="stat_classement_service_par_annee"),
    path('stat-nature-conge-annee', views.stat_nature_conge_annee, name="stat_nature_conge_annee"),
    path('send-email', views.sendEmail, name='sendEmail')
]

ProjectGestionPersonnel/urls.py
from django.contrib import admin
from django.conf.urls import handler403, handler404,handler500
from django.urls import path,include
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("AppAccount.urls")),
    path('personnel/', include('AppPersonnel.urls')),
    path('conge/', include('AppConge.urls')),
    path('planning/', include('AppPlanning.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler403 = "AppAccount.views.page403"
handler404 = "AppAccount.views.page404"
handler500 = "AppAccount.views.page500"

AppAccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission
from AppPersonnel.models import Grade, Fonction




class Personnel(AbstractUser):
    """Classe permet de stocker les informations des personnels"""
    username=models.CharField(max_length=155)
    postnom=models.CharField(max_length=155)
    prenom=models.CharField(max_length=155)
    email=models.EmailField(max_length=155, unique=True)
    TYPE_SEXE = (("M", "M"), ("F", "F"))
    ETAT_CIVIL = (("M", "M"), ("C", "C"), ("V", "V"))
    SALAIRE=(
        ('Oui', 'Oui'),('Non', 'Non')
    )
    PRIME=(
        ('Oui', 'Oui'),('Non',"Non")
    )
    matricule = models.CharField(max_length=255, unique=True, blank=True, null=True)
    sexe = models.CharField(max_length=1, choices=TYPE_SEXE, default="M")
    grade = models.ForeignKey(Grade, on_delete=models.PROTECT,blank=True, null=True)
    fonction = models.ForeignKey(Fonction, on_delete=models.PROTECT,blank=True, null=True)
    date_naissance = models.DateField(blank=True, null=True)
    date_engagement = models.DateField(blank=True, null=True)
    photo = models.ImageField(blank=True, null=True)
    salaire = models.CharField(max_length=3, choices=SALAIRE, default="Non")
    prime = models.CharField(max_length=3, choices=PRIME, default="Non")
    etat_civil = models.CharField(max_length=1, choices=ETAT_CIVIL, default='C')
    demandeur=models.BooleanField(default=False)
    approbateur=models.BooleanField(default=False)
    consulteur=models.BooleanField(default=False)
    sbgr=models.BooleanField(default=False)
    planificateur=models.BooleanField(default=False)
    date_creation=models.DateTimeField(auto_now_add=True)
    date_modification=models.DateTimeField(auto_now=True)

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['username', 'postnom', 'prenom',"sexe","etat_civil"]


    def __str__(self):
        return f"{self.username} {self.postnom} {self.prenom}"
    
    @property
    def getPersonnel(self):
        """Cette méthode permet de recuperer les personnels"""
        return f'{self.username} {self.postnom} {self.prenom}'

    @property
    def getPersonnelLogin(self):
        """Cette méthode permet de recuperer les personnels"""
        return f'{self.prenom.lower()} {self.username.lower()}'

    @property
    def getNombreDemandeConge(self):
        conge_user=self.conge_set.all()
        number_total=len([ligne.personnel for ligne in conge_user])
        return number_total

       
    

AppAccount/forms.py
from django import forms
from .import models
from django.contrib.auth.forms import (PasswordChangeForm,
                                       PasswordResetForm,
                                       SetPasswordForm)


class FormLogin(forms.Form):
    """Formulaire de connexion du personnel"""
    email=forms.CharField(widget=forms.EmailInput(attrs={"class":'form-control', 'placeholder':'Email'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={"class":'form-control','placeholder':'Password'}))
    se_souvenir_de_moi=forms.BooleanField(required=False)

class FormChangePassword(PasswordChangeForm):
    """Formulaire de changement de mot de passe du personnel"""
    old_password=forms.CharField(widget=forms.PasswordInput(attrs={"class":'form-control'}))
    new_password1=forms.CharField(widget=forms.PasswordInput(attrs={"class":'form-control'}))
    new_password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":'form-control'}))

class Formpassword_reset(PasswordResetForm):
    """Formulaire de demande de reinitialisation du mot de passe"""
    email=forms.CharField(widget=forms.EmailInput(attrs={"class":'form-control', 'placeholder':'Email'}))


class FormSetPassword(SetPasswordForm):
    """Formulaire de confirmation du nouveau mot de passe"""
    new_password1=forms.CharField(widget=forms.PasswordInput(attrs={"class":'form-control', 'placeholder':'Nouveau Mot de passe'}))
    new_password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":'form-control','placeholder':'Confirmer le Mot de passe'}))


class FormContact(forms.Form):
    """"Formulaire de Contact"""
    nom=forms.CharField(widget=forms.TextInput(attrs={"class":'form-control'}))
    email=forms.CharField(widget=forms.EmailInput(attrs={"class":'form-control'}))
    message=forms.CharField(widget=forms.Textarea(attrs={"class":'form-control', 'rows':'3'}))


class ChangeProfilUser(forms.ModelForm):
    """Formulaire de changement de photo de profil du personnel"""
    class Meta:
        model=models.Personnel

        fields=['photo']

AppAccount/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from .import models
import sweetify
from .import forms




def loginUser(request):
    """Connexion de l'utilisateur au système """
    if request.user.is_authenticated :
        return redirect('dashboard')
    form=forms.FormLogin()
    if request.method == "POST":
        form=forms.FormLogin(request.POST)
        if form.is_valid():
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            user=authenticate(email=email, password=password)
            if not "@" in email:
                messages.warning(request, "Adresse Email incorrect")
            elif user:
                login(request, user)
                return redirect('dashboard')
            else:
                messages.error(request, "Authentification échouée Merci de ressayer !")
        else:
            messages.error(request, "Oups ! Formulaire invalide")
    else:
        form=forms.FormLogin()
    return render(request, "login/login.html",{"form":form})

@login_required
def logoutUser(request):
    """Deconnexion du Personnel"""
    logout(request)
    messages.info(request, "Vous êtes déconnecté !")
    return redirect('index')

def page403(request, exception):
    """Page 403 personnalisée permissions requises"""
    return render(request, "error/page_403.html")


def page404(request, exception):
    """Page 404 personnalisé page introuvable !"""
    return render(request, "error/page_404.html")

def page500(request):
    """Page 500 Personnalisé erreur du Serveur"""
    return render(request, "error/page_500.html")


@login_required
def changePassword(request):
    """Changement du Mot de passe du Personnel"""
    form=forms.FormChangePassword(request.user)
    if request.method == "POST":
        form=forms.FormChangePassword(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "Vous êtes maintenant deconnecté, votre mot de passe a été changé, connectez-vous à nouveau !")
            return redirect('index')
        else:
            messages.error(request, "Formulaire invalide, veuillez renseigner les champs correctement !")
    else:
        form=forms.FormChangePassword(request.user)
    return render(request, "password/passwordchange.html",{"form":form})



def appropos(request):
    """Appropos de l'éblissement"""
    return render(request, "appropos/appropos.html")

def contact(request):
    """Page des Contacts"""
    form=forms.FormContact()
    return render(request, "contact.html", {"form":form})


@login_required
def ProfilUser(request):
    """Profil du personnel/Informations"""
    return render(request, "profil/profilUser.html")

@login_required
def ChangeProfil(request, id):
    """Changement ou suppression du Profil/Photo du personnel"""
    get_user=models.Personnel.objects.get(id=id)
    if get_user != request.user:
        return render(request,"error/page_403.html")
    form=forms.ChangeProfilUser(instance=get_user)
    if request.method == "POST":
        form=forms.ChangeProfilUser(request.POST, request.FILES, instance=get_user)
        if form.is_valid():
            form.save()
            messages.warning(request, "Votre photo a été mise à jour !")
            return redirect('ProfilUser')
        else:
            messages.warning(request, "Impossible de modifier votre photo")
    else:
        form=forms.ChangeProfilUser(instance=get_user)
    context={
        "get_user":get_user,
        'form':form
    }
    return render(request, "profil/changeProfil.html", context)

@login_required
def guideUser(request):
    """Guide d'utilisation descriptif du site !"""
    return render(request, "guide/guideUser.html")

AppAccount/templates/profil/changeProfil.html
{% extends "base/base.html" %}
{% block content %}

<style>
    .content{
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        flex-direction: column;
        box-shadow: 1px 1px 2px 1px rgba(0, 0, 0, 0.25);
        padding: 20px;
        margin-right: 8px;
    }
    .content form{
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        flex-direction: column;
        box-shadow: 1px 1px 2px 1px rgba(0, 0, 0, 0.25);
        padding: 20px;
        width: 100%;
    }
    .content form button{
        margin-top: 15px;
        padding: 10px;
    }
    .content form #id_photo{
        border: 1px solid rgb(243, 231, 234);
        padding: 10px;
        border-radius: 5px;
    }

    @media(max-width:423px){
        .content{
            margin-left: 2px;
            width: 98%;
            margin-right: 2px;
            padding: 5px;
            box-shadow: none;
        }
        .content form{
            display: flex;
            justify-content: flex-start;
            align-items: flex-start;
            flex-direction: column;
            overflow: hidden;
            width: 100%;
            margin-right: 0;
        }
    }
</style>


<div class="content">
    <div class="texte-content">
        <p>Changer ou supprimer votre photo</p>
    </div>
    <div class="messages">
        {% for message in messages %}
          <div class="alert alert-warning" role="alert">
            <p>{{message}}</p>
          </div>
        {% endfor %}
    </div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-info btn-block">Changez ?</button>
    </form>
</div>
  
{% endblock content %}

AppAccount/templates/profil/profilUser.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<style>
    .profils{
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        box-shadow: 1px 1px 2px 1px rgba(0, 0, 0, 0.25);
        margin-right: 7px;
    }
    .content {
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        flex-direction: column;
        box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.15);
        width: 100%;
        padding-left: 35px;
        padding-top: 30px;

    }

    .content .contenu {
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        flex-wrap: wrap;
        flex-direction: column;
        padding: 10px;
        margin-right: 20px;
        margin-top: 15px;
    

    }

    .content .contenu .link {
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        padding-bottom: 15px;
        width: 100%;
    }

    .content .contenu form {
        width: 100%;
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        flex-direction: column;
    }

    .content .contenu form input {
        width: 100%;
        border: 1px solid cadetblue;
        margin-bottom: 10px;
        padding: 25px;
    }

    .content .contenu .link a {
        margin-bottom: 20px;
        margin: 7px;
        padding: 20px;
    }

    .content .contenu table {
        width: 100%;
    }

    .content .contenu table tr th {
        background-color: rgb(106, 118, 126);
        color: white;
    }

    .content-img {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 25px;
    }

    .content-img .img {
        width: 190px;
        height: 190px;
        margin-bottom: 50px;
    }

    .content-img .img img {
        width: 100%;
        height: 100%;
        border-radius: 50%;
        object-fit: cover;
        object-position: center center;
    }

    .content-img .img p {
        margin-top: 10px;
        text-align: center;
    }


    @media(max-width:530px) {
    .profils{
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        box-shadow: 1px 1px 2px 1px rgba(0, 0, 0, 0.25);
        margin: 7px;

    }
    .content {
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        flex-direction: column;
        box-shadow: 1px 1px 2px 1px rgba(0, 0, 0, 0.25);
        width: 100%;
        padding-left: 35px;
        padding-top: 30px;

    }
    .content-img .img {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        width: 100%;
        height: auto;
        margin-bottom: 10px;
    }

    .content-img .img img {
        width: 50%;
        height: auto;
        border-radius: 50%;
        object-fit: cover;
        object-position: center center;
    }
    }
</style>

<div class="profils">
    <div class="content-img">
        {% if user.is_authenticated %}
        <div class="img">
            {% if user.photo %}
            <img src="{{user.photo.url}}" alt="">
            <p>Crée dépuis : {{user.date_creation}}</p>
            <a href="{% url 'ChangeProfil' user.id %}"><span class="fa fa-pencil"></span> Changer mon profil</a>
            {% else %}
            <img src="{% static 'assets/img/userlogo.png' %}" alt="">
            <p>Crée dépuis : {{user.date_creation}}</p>
            <a href="{% url 'ChangeProfil' user.id %}"> <span class="fa fa-pencil"></span> Changer mon profil</a>
            {% endif %}
            <hr>
        </div>

        {% endif %}
    </div>
    <div class="content">
        <div class="titre">
            <p>Tes informations ou Profils</p>
        </div>
        <div class="messages">
            {% for message in messages %}
              <div class="alert alert-warning" role="alert">
                <p>{{message}}</p>
              </div>
            {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <div class="infos-personnels">
            <ul>
                <li>Matricule : {{user.matricule}}</li>
                <li>Nom : {{user.username}}</li>
                <li>Post Nom : {{user.postnom}}</li>
                <li>Prénom : {{user.prenom}}</li>
                <li>Sexe : {{user.sexe}}</li>
                {% if user.grade %}
                <li>Grade : {{user.grade}}</li>
                {% endif %}
                {% if user.fonction.designation %}
                <li>Fonction : {{user.fonction.designation}}</li>
                {% endif %}
                {% if user.fonction.service %}
                <li>Service : {{user.fonction.service.designation}}</li>
                {% endif %}
                {% if user.date_naissance %}
                <li>DateNaissance : {{user.date_naissance}}</li>
                {% endif %}
                {% if user.date_engagement %}
                <li>DateEngagement : {{user.date_engagement}}</li>
                {% endif %}
                <li>Salarié(e) : {{user.salaire}}</li>
                <li>Primé(e) : {{user.prime}}</li>
                <li>Etat Civil : {{user.etat_civil}}</li>
                <li>Email : {{user.email}}</li>
              </ul>
            <hr>
        </div>
        {% endif %}
    </div>
</div>


{% endblock content %}